### ISSUE TITLE
Allow to use string event type names instead of class instances for subscriptions

### ISSUE THREAD

**Issue by swilgosz** [yousty/event_store_client#5]
### Overview

Allow to subscribe to event types using either: Event Class or the Stringified event type.

### Reason

When implementing the simple subscribe-only applications, there is no need to implement event classes. 

Also, there should not be a situation, where a two different microservices have different implementations of the same events (i.e. different data sets)

The service should only implement the events it publishes. And for subscribes, it should use the default general Event class, that comes with the gem: `EventStoreClient::Event`

### Example of usage

`client.subscribe(MyHandler, to: ['JobAdTitleChanged'])`

**Comment by ncri** [comment]
PR: https://github.com/yousty/event_store_client/issues/5
