### ISSUE TITLE
Cannot connect to eventstore cloud

### ISSUE THREAD

**Issue by dmadouros** [yousty/event_store_client#53]
Hi.

I'm trying to connect to eventstore cloud from my local machine using a rails app (no docker on client; no cluster on server). I'm trying to do a simple read on the `$all` stream, filtering by category.

However, when I do this I get the following error:

```
14:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:xx.xx.xxx.xxx:2113: FD shutdown. debug_error_string:{UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:xx.xx.xxx.xxx:2113: FD shutdown {created_time:"2022-11-29T11:31:07.529161-07:00", grpc_status:14}} (GRPC::Unavailable)
```

I've cracked open the code and determined that it seems to be caused by the following code in `connection.rb`:

```
def channel_args
  {
    # disable build-in GRPC retries functional
    'grpc.enable_retries' => 0,
    # These three options reduce delays between failed requests.
    'grpc.min_reconnect_backoff_ms' => 100, # milliseconds **THIS LINE SEEMS TO BE THE PROBLEM**
    'grpc.max_reconnect_backoff_ms' => 100, # milliseconds
    'grpc.initial_reconnect_backoff_ms' => 100 # milliseconds
  }
end
```

If I adjust the `grpc.min_reconnect_backoff_ms` to be ~200ms, the error goes away and everything works beautifully.

Would a PR to make this (or the whole group) configurable be desirable?

**Comment by intale** [comment]
@dmadouros hey

Hm. Could you provide the steps/repo where I can reproduce an issue? Those settings are mostly set to disable "retries" implementation of grpc. It works a bit unpredictable.

**Comment by dmadouros** [comment]
@intale 

Thanks for responding. Here's the repo: https://github.com/dmadouros/esdb_cloud_spike
Specifically, I've been playing in this file: https://github.com/dmadouros/esdb_cloud_spike/blob/main/app/eventstore/subscriptions.rb

BTW, It works fine when I'm running event store locally via docker. I only hit this issue when reaching out to eventstore cloud. 

I saw a slightly different error when I set the `grpc.min_reconnect_backoff_ms` to ~150ms that makes me think there might be some overhead or network latency in `grpc` that takes more than 100ms (🤷‍♂️ ):

```
14:failed to connect to all addresses; last error: UNKNOWN: ipv4:10.10.200.139:2113: connection attempt timed out before receiving SETTINGS frame. debug_error_string:{UNKNOWN:failed to connect to all addresses; last error: UNKNOWN: ipv4:10.10.200.139:2113: connection attempt timed out before receiving SETTINGS frame {created_time:"2022-12-01T12:58:50.694726-07:00", grpc_status:14}} (GRPC::Unavailable)
```

**Comment by intale** [comment]
@dmadouros, are you sure your cloud server is reachable from the outside? And what error do you receive when you set `grpc.min_reconnect_backoff_ms` to greater value?

**Comment by dmadouros** [comment]
@intale No error if I increase it. Everything works.

**Comment by intale** [comment]
@dmadouros so did you figure out what was the issue?

**Comment by dmadouros** [comment]
@intale I don't feel like I understand the root cause. Bumping `grpc.min_reconnect_backoff_ms` to 200ms appears to fix it. I'm a little concerned that if it is some type of network latency, 200ms works right now, but maybe not in the future depending on network latency in other environments. Given that, I see two options:

1. Create a PR and set it to 200ms and hope for the best
2. Create a PR and make it configurable

Do either of those sound appealing to you?

**Comment by intale** [comment]
@dmadouros I don't understand it either. I don't quite understand how backoff strategy affects on this issue. I guess I'll just allow to adjust those values in the config. Approximate release day - Monday. Thank you for the report.

**Comment by intale** [comment]
@dmadouros btw, concerning subscriptions - you could try another gem, which is based on this gem. It implements an interface to simplify ES subscriptions usage https://github.com/yousty/event_store_subscriptions

**Comment by dmadouros** [comment]
@intale Excellent. Sounds like you're gonna do the fix and don't need a PR from me? 

Also, thanks for the suggestion regarding the subscriptions repo! We were wondering how `Thread.new` would plan with rails and starting to think about how we might deal with thread management. Looks like you've got it covered! We'll definitely be trying that out.

It's been a pleasure communicating with you on this issue 😄. And thanks for creating/maintaining these libraries!

**Comment by intale** [comment]
@dmadouros done. Try to install `event_store_client` v2.2.0. There you are able to configure channel arguments. Example:

```ruby
EventStoreClient.configure do |config|
  config.channel_args = { 'grpc.min_reconnect_backoff_ms' => 200config.channel_args = { 'grpc.min_reconnect_backoff_ms' => 200 } }
end
```

You may want to check the updated [configuration docs](https://github.com/yousty/event_store_client/blob/v2.2.0/docs/configuration.md) as well.

**Comment by dmadouros** [comment]
Works like a charm. Thanks!

I checked out the configuration docs -- looks good to me.
